### PR TITLE
New controls

### PR DESCRIPTION
**Pull request by mnblonsky**
Addresses #103 and #77

- [x] Reference the issue your PR is fixing
- [x] Assign at least 1 reviewer for your PR
- [x] Test with run_dwelling.py or other script
- [x] Update documentation as appropriate
- [x] Update changelog as appropriate

### CODE REVIEW

**Comment by mnblonsky** [comment]
Note that Max Power for HPWH won't work for HP mode. It's tricky to implement for long time steps when the HPWH is in HP mode part time and ER mode part time. We probably want to limit the average power across the time step, which could mean lowering the ER time and increasing the HP time. Might be best to keep this out for now until there's a need.

**Comment by jmaguire1** [comment]
> Note that Max Power for HPWH won't work for HP mode. It's tricky to implement for long time steps when the HPWH is in HP mode part time and ER mode part time. We probably want to limit the average power across the time step, which could mean lowering the ER time and increasing the HP time. Might be best to keep this out for now until there's a need.

Agreed, I think we just don't allow this for the time being, unless there's a real need for it. Most of the time the HP will be sufficient to meet the loads, especially at long timesteps, but not always.

**Comment by mnblonsky** [comment]
Noting that Max Capacity (and direct Capacity) is added for HVAC, and Max Power is added for Water Heating. We don't have plans to add both of those options for both end uses, because:
 - Max Power seems more useful, and there isn't a great use case for setting Capacity for water heaters
 - Max Power is very hard to do for HVAC, given the dependence on the envelope and the biquadratic functions for EIR. We could estimate or iterate, but it seems like a low priority for now. The Max Capacity Fraction is arguably pretty close to a "Max Power Fraction", so lets try that for now.

I'm moving on to EV/PV/Battery controls now.

**Comment by mnblonsky** [comment]
Added a few battery controls to the list. I don't think we'll need controls for min/max power limits, there's no known use case for that. Only EV and PV left!

**Comment by mnblonsky** [comment]
Added EV controls. I'm going to skip PV controls for now, since there's no current need for it. The most useful PV control might be some sort of non-export control that limits PV to the house load (e.g., if there's no battery and no grid exports are allowed). But I think we should hold off on that until it's necessary.

**Comment by mnblonsky** [comment]
Just finished building the docs, they're looking good now. @jmaguire1, this is ready for your review.

**Review by jmaguire1 — APPROVED** [review]
Looks good! I reviewed some of this already, I don't have much to add here. Nice to see some new examples showcasing even more of the flexibility OCHRE gives you.

**Pull request merged**
